version: '3.8'

services:
  db-postgres:
    image: postgres:latest
    container_name: db-app-container
    ports:
      - '54321:5432'
    environment:
      POSTGRES_PASSWORD: 'psql'
      POSTGRES_DB: 'db_app'
      POSTGRES_USER: 'root'
    volumes:
      - '~/Downloads/DatasourceVolume:/var/lib/postgresql/data'

  spring-app:
    build: .
    depends_on:
      - db-postgres
    container_name: spring-app-container
    ports:
      - '8081:8080'
    environment:
      DATASOURCE_HOST: db-postgres
