spring:
  application:
    name: g34-spring-boot-caching
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:5432/db_app
    username: root
    password: psql
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
