spring:
  application:
    name: g34-spring-boot-caching
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: b1t
    password: 1596psql
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

